### ISSUE TITLE
Vue beginner not sure how to setup the component

### ISSUE THREAD

**Issue by kickthemooon** [Eazymov/vue-mce#10]
How I would like to use it:
```
import VueMce from 'vue-mce';
Vue.component('mce', VueMce );
```
and then just use it like:
```
<vue-mce :config="config" v-model="myValue" />
```

But I am not sure here if I can do that.
If not I guess I have make a "mce.vue" component but I am not sure how to do that.

**Comment by Eazymov** [comment]
`VueMce` it is plugin that have to be passed to `Vue.use`
To import `component` use `import { component } from 'vue-mce'` and `Vue.component('vue-mce', component)`
