### ISSUE TITLE
vue-mce not working in my Laravel

### ISSUE THREAD

**Issue by TholthoeunChansovann** [Eazymov/vue-mce#12]
Hi, i try using vue-mce but after installed it not work it show me blank. How i can do it?

**Comment by Eazymov** [comment]
Did you include tinymce in your project? Is it available via window.tinymce?

**Comment by TholthoeunChansovann** [comment]
How to do it? Install tinymce first right?

**Comment by TholthoeunChansovann** [comment]
add like this right?

import tinymce from 'tinymce';
Vue.use(tinymce);
import VueMce from 'vue-mce';
Vue.use(VueMce);

**Comment by Eazymov** [comment]
For example:

```html
<!DOCTYPE html>
<html>
<head>
  <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
  <script>tinymce.init({ selector:'textarea' });</script>
</head>
<body>
  <textarea>Next, start a free trial!</textarea>
</body>
</html>
```

**Comment by TholthoeunChansovann** [comment]
it show me like this "/js/themes/modern/theme.js net::ERR_ABORTED"

**Comment by Eazymov** [comment]
How you include tinymce?

**Comment by TholthoeunChansovann** [comment]
like this 
import tinymce from 'tinymce';
Vue.use(tinymce);

**Comment by Eazymov** [comment]
it cant be installed this way, take a look at example above

**Comment by TholthoeunChansovann** [comment]
@Eazymov Thank for help now it working :)
