### ISSUE TITLE
Component not rendering

### ISSUE THREAD

**Issue by RarexWU16** [Eazymov/vue-mce#15]
Hello!

I can see that the component is loaded and have recieved my config, using the vue devtools for Chrome.
But for some reason it just doesn't render.

```
import Vue from 'vue';
import VueMce from 'vue-mce';
 
Vue.use(VueMce);
```
`<vue-mce name="content" :initial-value="card.content" :config="mceconfig" v-model="card.content" />`

I'm using TypeScript and Webpack... And I'm really new to both of them, maybe there is some kind of standard configuration I have to do?

**Comment by Eazymov** [comment]
Hi,

Have you included tinymce in your project? Is it available via window.tinymce?

**Comment by monochromatique** [comment]
the same

**Comment by monochromatique** [comment]
when as a plugin 

window.tinymce

is undefined

**Comment by monochromatique** [comment]
got this in handleError

err = Error: TinyMce wasn't found at VueComponent.mounted (webpack-internal:///725:1:7106)

**Comment by Eazymov** [comment]
Please note that vue-mce doesn't provide any tinymce build by default. You must include tinymce by yourself. If it is, make sure that tinymce is loaded **before** your script

**Comment by RarexWU16** [comment]
I see, I had not included TinyMCE. I ran npm install to get tinymce but they miss a typedeclaration so I can't load it. But I guees you don't do support for TinyMCE!

Thanks alot for the answer!

**Comment by Eazymov** [comment]
You can include tinymce via script tag

```html
<script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
```

**Comment by RarexWU16** [comment]
Oh okay, that worked! Thanks alot!
