### ISSUE TITLE
remove() and init()

### ISSUE THREAD

**Issue by ercanertan** [Eazymov/vue-mce#22]
I am adding tinymce to the DOM dynamically. 
How can I remove all initiated tinymce and re init again every time I add new tinymce?

handleInit (editor) {
      editor.remove();   // this works
      editor.init(); // this doesn't work
}

**Comment by Eazymov** [comment]
@ercanertan Hi, you can add common `key` prop to each of your vue-mce component and update this key every time you add a new one, this will remount all vue-mce components

**Comment by ercanertan** [comment]
I appreciate your time to respond, 
I am new to vuejs and trying to setup a bit of complex page with [vuedraggable](https://github.com/SortableJS/Vue.Draggable) package. Maybe issue is other package.

**Comment by ercanertan** [comment]
I will close this until I confirm the issue within this package!
