### ISSUE TITLE
dependencies are now locked to specific versions

### ISSUE THREAD

**Issue by SunnysideAaron** [Eazymov/vue-mce#23]
during the 1.5.1 release of vue-mce it appears that all the dependencies got locked to specific patch versions. checking your packages.json file it appears that instead of "vue": "^2.5.3" is now "vue": "2.5.3" this means that even though we are using vue 2.5.21 we still get the warning: `npm WARN vue-mce@1.5.2 requires a peer of vue@2.5.3 but none is installed. You must install peer dependencies yourself.`
when running `npm install vue-mce`

This seems to be the case with all the dependencies in package.json

**Comment by Eazymov** [comment]
Hi, thanks for the feedback, i'll update `package.json` today/tomorrow

**Comment by Eazymov** [comment]
Updated in 1.5.3
