### ISSUE TITLE
can you add emoji and suggestion to this package?

### ISSUE THREAD

**Issue by nekooee** [Eazymov/vue-mce#25]
Hi Dear,
can you add emoji to this package, please? like this:
![image](https://user-images.githubusercontent.com/6003803/67418082-027c8700-f5d7-11e9-9ac5-d6fc7bfd7880.png)

and suggestion like this:

![image](https://user-images.githubusercontent.com/6003803/67422297-07453900-f5df-11e9-8856-d4f6ffda0873.png)

**Comment by Eazymov** [comment]
Hi,

`vue-mce` library doesn't control which plugins to use, it is configured via tinymce config

Regards
