### ISSUE TITLE
Error: TinyMce was not found

### ISSUE THREAD

**Issue by nekooee** [Eazymov/vue-mce#26]
Hi Dear,
I add the component to my site like this:

```javascript
import Editor from '@tinymce/tinymce-vue'
Vue.use(Editor);

import VueMce from 'vue-mce';
Vue.use(VueMce);
```

but I get this error:
Error: TinyMce was not found
please help me.

**Comment by nekooee** [comment]
I add require like this:
```javascript
require('./files/tinymce.min');
import VueMce from 'vue-mce';
Vue.use(VueMce);
```
work fine but show warning message:

> This domain is not registered with TinyMCE Cloud. Start a free trial to discover our premium cloud services and pro support.

**Comment by Eazymov** [comment]
Hi,

If you use `@tinymce/tinymce-vue` you don't have to use `vue-mce` and vice-versa
If you prefer `vue-mce` then you have to add the tinymce script to your page (it should be accessible via `window.tinymce`)

This error:
>This domain is not registered with TinyMCE Cloud. Start a free trial to discover our premium cloud services and pro support.

Related to tinymce script, not `vue-mce` library

Regards
