### ISSUE TITLE
TinyMce

### ISSUE THREAD

**Issue by Zikoi5** [Eazymov/vue-mce#27]
your plugin say's TinyMce is not defined

![image](https://user-images.githubusercontent.com/12369295/67879760-52bb9200-fb5f-11e9-8c3b-ea402e00ed5e.png)

I've imported all to need tinymce

```
import VueMce from 'vue-mce';
Vue.use(VueMce);
```

in app.vue
```<vue-mce :config="tinyVueMceConf"/>```

```
tinyVueMceConf: {
theme: 'modern',
        fontsize_formats: "8px 10px 12px 14px 16px 18px 20px 22px 24px 26px 39px 34px 38px 42px 48px",
        plugins: 'print preview fullpage powerpaste searchreplace autolink',
        toolbar1: 'formatselect fontsizeselect | bold italic strikethrough forecolor backcolor link',
}
```

**Comment by Eazymov** [comment]
Hi,

TinyMce should be available as `window.tinymce`
For example via `<script />` tag:
```html
<script src="https://path/to/tinymce.js"></script>
```

Regards
