### ISSUE TITLE
How to add button toolbar

### ISSUE THREAD

**Issue by nguyenvanthinh06** [Eazymov/vue-mce#28]
Hello Admin!
sorry.... I can not speak English very well...

how to add custom buttons? like image upload, ...,

**Comment by Eazymov** [comment]
Tinymce v4 - https://www.tiny.cloud/docs-4x/configure/file-image-upload/
Tinymce v5 - https://www.tiny.cloud/docs/configure/file-image-upload/

**Comment by nguyenvanthinh06** [comment]
@Eazymov Thank you very much!
