### ISSUE TITLE
Refused to apply style from 'http://localhost:8081/skins/lightgray/content.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

### ISSUE THREAD

**Issue by egontrimfa** [Eazymov/vue-mce#29]
The following toolbar items are not working: "forecolor backcolor link".
I have read about it and I found out that I have to change my webpack cofiguration.
How so?

**Comment by Eazymov** [comment]
This is not related to vue-mce
