### ISSUE TITLE
inline: true

### ISSUE THREAD

**Issue by CodeOfDavid** [Eazymov/vue-mce#3]
If i add 

const config = {
  **inline: true,**

The inline doesn't render.

**Comment by Eazymov** [comment]
Thanks for the feedback!

Problem is fixed in #1.3.2

**Comment by CodeOfDavid** [comment]
Thanks, I tried the demo at https://codepen.io/Eazymov/pen/MEzGYv with inline: true. It did not work.

**Comment by Eazymov** [comment]
It's just jsdelivr caching, I changed version in codepen settings and now it works

**Comment by CodeOfDavid** [comment]
Perfect, thanks!

**Comment by CodeOfDavid** [comment]
If setting inline: true then when typing the cursor goes to the beginning of the textbox

**Comment by Eazymov** [comment]
Fixed in 1.3.3
