### ISSUE TITLE
How to inserting outer text in VUEMCE Editor where the cursor is?

### ISSUE THREAD

**Issue by bhavini-chauhan** [Eazymov/vue-mce#49]
There is a text which is outside the editor By clicking on it, this will add where the cursor is located.
The outer text will be multiple.

**Comment by Marchiuzzz** [comment]
Have the same question, have you ever figured this out?

**Comment by Eazymov** [comment]
Doesn't Ctrl+C/Ctrl+V work in this case?

**Comment by Marchiuzzz** [comment]
Well in my case I needed to programmatically insert an image at current cursor position of the editor, managed to achieve that with this code
```
//items is an array of image objects (my custom objects)
addImages(items){
            let images = items.map(el => el.image); //el.image is the src of image
            let ed = tinymce.activeEditor;             // get editor instance
            images.map(el => {
                let range = ed.selection.getRng();                  // get range
                let newNode = document.createElement("img");  // create img node
                newNode.src = el;                           // add src attribute
                newNode.classList.add('img');
                newNode.classList.add('h-auto');
                range.insertNode(newNode); 
            });
        }
```
This probably wouldn't work correctly if I had more than one editor open at a time but since I won't do that, this does the trick.

**Comment by Eazymov** [comment]
@Marchiuzzz tinymce also has this API https://www.tiny.cloud/docs-4x/advanced/editor-command-identifiers/
![image](https://user-images.githubusercontent.com/26853518/141991236-52f249b6-7c04-480f-81d8-a64aa52b6be6.png)

**Comment by Marchiuzzz** [comment]
@Eazymov Oh, I didn't know about this as I'm new to tinymce. Thanks!
