### ISSUE TITLE
Unexpected token: punc (() from UglifyJs

### ISSUE THREAD

**Issue by giovannigenna** [Eazymov/vue-mce#8]
Hello,
When I try to build my app with NPM RUN BUILD command, the response from terminal is: 
`ERROR in static/js/vendor.fd125947db1218b759b7.js from UglifyJs
Unexpected token: punc (() [./node_modules/vue-mce/dist/vue-mce.common.js:1,823][static/js/vendor.fd125947db1218b759b7.js:62883,800]`

If I run it with NPM RUN DEV, it works perfectly. I have try to create a new project with VUE CLI, so I use the last version of webpack, vue, etc. , but I get this error when I try to build my project.

Can u help me ?
Giovanni

**Comment by Eazymov** [comment]
Hello!
I made some changes and released package under 1.3.6 version
Tested it with vue-cli `webpack` template

**Comment by giovannigenna** [comment]
Good Job!
Now it works great!

Thanks about this awesome plugin ;)
