### ISSUE TITLE
Not initialize in nuxt js

### ISSUE THREAD

**Issue by hanjeahwan** [Eazymov/vue-mce#9]
![image](https://user-images.githubusercontent.com/21311478/34431131-4cd70c70-eca7-11e7-8bcb-97c65e6061cb.png)

![image](https://user-images.githubusercontent.com/21311478/34431122-2f8959fc-eca7-11e7-8812-11c106df42e3.png)

**Comment by Eazymov** [comment]
Hi

Looks like tinymce wasn't found
Make sure that tinymce available as global variable
You can listen for error with @error="yourLogMethod" and see the error message

Regards
